### ISSUE TITLE
Handling negative values

### ISSUE THREAD

**Issue by nevotens** [briandconnelly/pyfttt#2]
If any value starts with "-" (e.g. "-52,7", "-a") pyfttt fails.

Se below:
Traceback (most recent call last):
  File "/home/pi/Documents/kutahaz.py", line 101, in <module>
    temp, humi, temp_k])
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pyfttt', '-k', '***', '-e', '***', '19,5', '-52,7', '-a']' returned non-zero exit status 2

**Comment by briandconnelly** [comment]
Strange! I'll try this out in the next few days and get it fixed.

Edit: I encountered the same error. See https://stackoverflow.com/questions/9025204/python-argparse-issue-with-optional-arguments-which-are-negative-numbers.
